# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "seed started"

# Kategori
c1 = Category.create(name: 'Biyografi-anı')
c2 = Category.create(name: 'Sanat-tasarım')
c3 = Category.create(name: 'Çocuk ve gençlik')
c4 = Category.create(name: 'Hobi')
c5 = Category.create(name: 'Bilim kurgu')
c6 = Category.create(name: 'Araştırma-tarih')
c7 = Category.create(name: 'Macera-polisiye')
c8 = Category.create(name: 'Romantik')

t1 = Tag.create(name: 'aşk')
t2 = Tag.create(name: 'sevgi')
t3 = Tag.create(name: 'dram')
t4 = Tag.create(name: 'korku')

s2 = Status.create(name: 'okuyorum')
s1 = Status.create(name: 'okudum')
s3 = Status.create(name: 'okuyacağım')
# Yazarlar
w1 = Writer.create(name: 'Walter Isaacson')
w2 = Writer.create(name: 'Hunter Davies')
w3 = Writer.create(name: 'Mahatma Gandhi')
w4 = Writer.create(name: 'Oliver Sacks')
w5 = Writer.create(name: 'David McCullough')
w6 = Writer.create(name: 'William Shakespeare')
w7 = Writer.create(name: 'Oğuz Atay')
w8 = Writer.create(name: 'Rauda Jamis')
w9 = Writer.create(name: 'Murat Meriç')
w10 = Writer.create(name: 'Samuel Beckett')
w11 = Writer.create(name: 'Antoine de Saint-Exupery')
w12 = Writer.create(name: 'Samed Behrengi')
w13 = Writer.create(name: 'Ferenc Molnar')
w14 = Writer.create(name: 'Jules Verne')
w15 = Writer.create(name: 'Hamdi Tuncer')
w16 = Writer.create(name: 'Don Miguel Ruiz')
w17 = Writer.create(name: 'Canan Efendigil Karatay')
w18 = Writer.create(name: 'Eckhart Tolle')
w19 = Writer.create(name: 'James Churchward')
w20 = Writer.create(name: 'Mehmet Ali Bulut')
w21 = Writer.create(name: 'Douglas Adams')
w22 = Writer.create(name: 'John Shirley')
w23 = Writer.create(name: 'George Mann')
w24 = Writer.create(name: 'Dmitry Glukhovsky')
w25 = Writer.create(name: 'Andy Weir')
w26 = Writer.create(name: 'Yuval Noah Harari')
w27 = Writer.create(name: 'Halil İnalcık')
w28 = Writer.create(name: 'İlber Ortaylı')
w29 = Writer.create(name: 'Hanefi Avcı')
w30 = Writer.create(name: 'Karl Marx')
w31 = Writer.create(name: 'Dan Brown')
w32 = Writer.create(name: 'Adam Fawer')
w33 = Writer.create(name: 'Ahmet Ümit')
w34 = Writer.create(name: 'Paula Hawkins')
w35 = Writer.create(name: 'Oliver Bowden')
w36 = Writer.create(name: 'Jojo Moyes')
w37 = Writer.create(name: 'Rainbow Rowell')
w38 = Writer.create(name: 'John Green')
w39 = Writer.create(name: 'Amy Harmon')
w40 = Writer.create(name: 'Haruki Murakami')

bs = []

[
  # Biyografi-anı
  {name: 'Steve Jobs', published_at: '21.02.2011', description: "'...Ama bu işi yapmak istememin tek sebebi şu: dünyanın Apple'la daha güzel bir yer olacağını düşünüyorum.' Steve Jobs, tekrar Apple'a dönmesi için yapılan teklifi değerlendirirken... Çok satan Benjamin Franklin ve Albert Einstein biyografilerinin yazarı Walter Isaacson, Apple'ın kurucularından Steve Jobs'ın, kendisiyle tam işbirliği içinde yazılmış tek biyografisini sunuyor.", publishing_house: 'Domingo Yayınevi', category_id: 1, writer_id: 1},
  {name: 'The Beatles', published_at: '13.08.2016', description: "Hunter Davies'in, Beatles'ın zirvede olduğu dönemde, 1967-1968 yıllarında, onlarla birlikte on sekiz ay geçirerek yazdığı The Beatles, grubun tek onaylı biyografisi olma özelliğini taşıyor. Kitap 'muhteşem dörtlü' John, Paul, George ve Ringo'nun yanı sıra, aileleri, okul arkadaşları, sevgilileri, menajerleri, birlikte çaldıkları diğer müzisyenler ve daha pek çok kişinin tanıklıklarını da içeriyor. ", publishing_house: 'Kara Plak', category_id: 1, writer_id: 2},
  {name: 'Bir Özyaşam Gandhi', published_at: '21.03.2016', description: "Mohandas K. Gandhi 1869'da Hindistan'da doğdu. Londra'da eğitim gördü ve daha sonra ırkçılığın en kötüsünü bizzat yaşadığı Güney Afrika'da avukatlık yapmaya başladı. Yaşarken İngilizler için bir suçlu, Müslümanlar için bir kahraman, Hindular içinse kutsal bir adamdı. Irkçılığa, sömürgeciliğe karşı gösterdiği pasif direnişle koca bir ulusu bağımsızlığa taşıyan, tarihin akışını değiştiren kişiliklerden biri oldu. Gandhi'nin yaşamının önemli olaylarını anlattığı bu kitap, yoluna bağlılığından ve dürüstlüğünden bir an olsun taviz vermeyen, değişime önce kendinden başlayan büyük bir ruhun büyüleyici bir portresi aynı zamanda. Bir insanı büyük bir insan yapan nedir sorusuna verilecek en güzel yanıtı Gandhi'nin kendi sözlerinden, Vedat Günyol'un Türkçesiyle okuyun. ", publishing_house: 'Alfa Yayıncılık', category_id: 1, writer_id: 3},
  {name: 'Hareket Halinde Bir Hayat', published_at: '21.03.2016', description: 'Dünya çapında ün kazanmasını sağlayan kitaplarında beyin ve sinir sisteminin tuhaflıklarını, insanın birbirinden zor durumlara uyum sağlayabilme becerisini anlatan Oliver Sacks, bu sefer kendini odağa alıyor. ', publishing_house: 'Yapı Kredi Yayınları', category_id: 1, writer_id: 4},
  {name: 'Wright Kardeşler', published_at: '21.03.2016', description: "Amerikalı ünlü tarihçi ve yazar David McCullough, Wright Kardeşlerin hikâyesini belgesel tadında okuyacağınız bu kitapta anlatmak için, kişisel günlüklerin, not defterlerinin ve binden fazla şahsi aile arası yazışmasının da içinde bulunduğu Wright belgelerinin geniş zenginliğinden ve kız kardeşleri Katharine'in pek bilinmeyen katkılarından yararlanıyor.", publishing_house: 'Lemur', category_id: 1, writer_id: 5},

  # Sanat-tasarım
  {name: 'Hamlet', published_at: '18.04.2008', description: "Oyunları ve şiirlerinde insanlık durumlarını dile getiriş gücüyle yaklaşık 400 yıldır bütün dünya okur ve seyircilerini etkilemeyi sürdüren efsanevi yazar, Hamlet'de aşk, akrabalık ve iktidar ilişkileri ile intikam arzusunu birbirini izleyen cinayetlerin örgüsünde ele alır. Kaynağı eski kuzey masallarına kadar uzanan bu tragedya sadece Shakespeare'in değil, dünya tiyatro tarihinin de en tanınmış eserlerindendir. Üzerine binlerce kitap yazılan Hamlet, çağımızda en çok sahneye konulan oyunlardan biri olmuştur.", publishing_house: 'İş Bankası Kültür Yayınları', category_id: 1, writer_id: 6},
  {name: 'Oyunlarla Yaşayanlar', published_at: '2004', description: "Tanzimat'tan bu yana sürekli değişen politik ve toplumsal değerler, hedefler, ölçütler Türk aydınını kronik bir bunalıma sürükledi. Oğuz Atay'ın tiyatro eseri, varoluş sorunlarıyla boğuşan ve 'tutunmaya' çabalayan ve bunu pek başaramayan okur-yazarımızın kara güldürüsü. Eylemsizlikle geçmiş bir hayatın doğal ürünü beceriksizlik ve gülünç olma korkusundan Atay sürükleyici bir oyun çıkarmış. Bir Bilim Adamının Romanı'nı yazdı. 'Oyunlarla Yaşayanlar' adlı tiyatro eseri Devlet Tiyatroları'nda sahnelendi. Atay 13 Aralık 1977'de, büyük projesi 'Türkiye'nin Ruhu'nu yazamadan hayata gözlerini yumdu.", publishing_house: 'İletişim Yayıncılık', category_id: 1, writer_id: 7},
  {name: 'Frida Kahlo Aşk ve Acı', published_at: '21.03.2016', description: "20. yüzyılın popüler ikonlarından ressam, devrimci ve feminist Frida Kahlo'nun eserleri sürrealist olarak tanımlansa da kendisi bu tanımı, 'Ben sürrealist bir ressam değilim. Asla hayallerimi resimlemedim. Yalnızca kendi gerçeğimi resimledim' diyerek reddetti. Sanat tarihinde ilk kez bir kadın, yalınlığı ve sakinliği acımasız denebilecek bir içtenlik ve rahatsız edicilikle dile getirdi.Tablolarının birçoğunda kendi yüzünden yola çıkan Frida'nın yaşamöyküsü bize, Carol Hanisch'in kült olmuş 'kişisel olan politiktir' mottosunun ne demek olduğunu anlatır. Çünkü o ruhunu kattığı Meksika devrimini doğum günü ilan eden bir marjinal, hiç doğmamış oğluna isim koyup onunla düşlerinde konuşan bir hayalperest, aldatılan kadın imajına da topluma direndi¤i gibi direnen bir savaşçı, tekerlekli sandalyeye mahkûm olduğunda bile ne sanatından ne de hayatından vazgeçmiş, tersine onları daha da yüceltmiş kutsal bir mücadeleci ve Diego Rivera ile yaşadığı aşkta, senin sevmediklerini de sevdim ben diyen taraftır. ", publishing_house: 'Everest Yayınları ', category_id: 1, writer_id: 8},
  {name: '100 Şarkıda Memleket Tarihi', published_at: '21.03.2016', description: "Tarih, okulda en uzak durduğum ders. Hayatımdaki tek bütünlemem, lise sonda girdiğim tarih bütünlemesi. Bugün tarihçi olarak anılıyor olmam, oldukça ironik bir durum. Bize öğretilen tarih, tanıklıklarda rastladığımız gibi değil. Tarihi şarkılarla bütünlemek, geçmişin izlerini şarkılarda sürmek, heyecanlı. Elinizde tuttuğunuz kitapta, bu heyecanı sizlerle paylaşıyorum. Kitap, kendini anlatıyor. Özeti şu: Memlekette ve dünyada olan biten üzerine yazılmış şarkılar var burada. Benim seçtiklerim. Başka biri bambaşka şarkılar seçebilirdi. Kitabı hazırlarken ve şarkıları sunarken kronolojik bir sırada ilerlemeyi tercih ettim. Yine de (okura bir kolaylık sağlamak için) kendimce önemli gördüğüm öbekleri ayırarak kimi bölümlemeler yaptım. Karışık gözükebilir, eksikleri/fazlaları vardır, olabilir. En büyük eksik, başta ayrı bir bölüm olarak tasarladığım seçim şarkıları. Başa çıkamayınca, eleyemeyince onları kitabın dışında bıraktım. Kim bilir, belki de bir sonraki kitabın konusu olurlar… 100 rakamı şüphesiz sınırlayıcı. İstemeden kitap dışında bıraktığım çok şarkı/olay var. Yine de kendimi tutamayıp 'fazladan' altı belgesel plak ekledim. Kitap dışında kalan şarkıları unuttuğum sanılmasın.", publishing_house: 'Ağaçkakan Yayınları', category_id: 1, writer_id: 9},
  {name: "Godot'yu Beklerken", published_at: '1954', description: "Godot'yu Beklerken 1948 yılında Fransızca olarak yazıldı ve 1953'te Paris'de sahneye kondu. Zamanla ülke çapında bir ün kazandı. 1954 yılında Beckett tarafından bazı değişikliklerle İngilizceye çevrildi ve başka ülkelerde de sahnelenmeye başladı. Avangard olarak nitelenmesine karşın hızla klasikleşti. Oyunun varoluş sancıları çeken kahramanları, yolları kesiştiğinde birbirleriyle iletişim kurmaya çalışırlar. Her gün yinelenen bu ritüelde bellek işlevinin yerine getiremeyince de gerçekliğin kesinliğinden uzaklaşmaya başlarlar. Kimilerine göre tüm zamanların en iyisi olan bu oyun, 21. yüzyılda da kafamızda soru işaretleri bırakmaya devam ediyor.", publishing_house: 'Kabalcı Yayınevi', category_id: 1, writer_id: 10},

  # Çocuk ve gençlik
  {name: 'Küçük Prens', published_at: '21.03.2016', description: "'Hoşça git,' dedi tilki. 'Vereceğim sır çok basit: İnsan ancak yüreğiyle baktığı zaman doğruyu görebilir. Gerçeğin mayası gözle görülmez.' Küçük Prens unutmamak için tekrarladı: 'Gerçeğin mayası gözle görülmez.'", publishing_house: 'Can Çocuk Yayınları', category_id: 2, writer_id: 11},
  {name: 'Küçük Kara Balık', published_at: '17.03.2016', description: 'Kış ortasında bir akşam vaktiydi. Denizin en derin yerinde, yaşlı mı yaşlı bir balık nine sayıları on iki bini bulan çocuklarıyla torunlarını çevresine toplamış, onlara bir masal anlatıyordu...', publishing_house: 'Can Çocuk Yayınları', category_id: 2, writer_id: 12},
  {name: 'Pal Sokağı Çocukları ', published_at: '17.03.2016', description: "Nemecsek, Boka ve Pál Sokağı'nın öbür çocukları 1907 yılında Budapeşte'nin yoksul Józsefváros semtinden yola çıktılar. Bugün artık bütün dünyada tanınıyorlar. Bugüne kadar her yaştan milyonlarca insan onların dokunaklı hikâyesini okudu; tıpkı Budapeşteli çocuklar gibi onlar da Boka'nın cesaretine hayran oldu, Nemecsek'in ürkek ama kararlı kahramanlığı karşısında gözyaşlarını tutamadı.Şimdi artık Pál Sokağı Çocukları'nın Arsa'sında kocaman çok katlı evler var. Ama ne gam: Dünyanın bütün çocukları Pál Sokağı'ndandır!", publishing_house: 'Yapı Kredi Yayınları', category_id: 2, writer_id: 13},
  {name: 'Seksen Günde Devriâlem', published_at: '18.07.2014', description: "Günümüzde bir dünya turu atmak için seksen gün gerekmeyebilir ama 1870'lerde, bu gezi neredeyse imkânsızdı. Yakın çevresinde düzenli bir yaşama sahip, titiz ve dakik biri olarak tanınan bir İngiliz beyefendisi olan Phileas Fogg, Reform Kulübü'ndeki arkadaşlarıyla servetini ortaya koyduğu bir iddiaya tutuşur ve bu geziyi seksen günde tamamlayacağını söyler. Geçmişi hakkında hiçbir şey bilinmeyen, zengin ve kibar Phileas Fogg'a yeni uşağı Jean Passepartout eşlik edecektir. Bay Fogg ve Passepartout, küçük bir gecikme ya da öngörülemeyen bir aksiliğin her şeylerini kaybetmelerine neden olacağı bir maceraya atılırlar. Seyahatleri sırasında bir sürü sorunla karşılaşır; değişik ülkelerden geçerken kimi zaman fil sırtında, kimi zaman tren ya da gemiyle yolculuk ederler. İddia sonucu giriştikleri bu yolculuk, kimi zaman serüven dolu bir kaçışa da dönüşecektir. Jules Verne'in (1828-1905) Seksen Günde Devriâlem'i, yayımlandığı 1872 yılından bu yana dünyada en çok okunan kitaplar arasında yer almaktadır. Birçok dile çevrilen, sinemaya da uyarlanan bu klasik eser, şimdi de Arkadaş Çocuk Kitapları, Gökkuşağı dizisinde.", publishing_house: 'Arkadaş Yayıncılık', category_id: 2, writer_id: 14},
  {name: 'Sonsuzluğun Ötesinde- Saklı Cennet', published_at: '16.06.2015', description: 'Gazete ve televizyonlarda UFO haberleri görüp de uzayın sonsuzluğu, evrenin gizleri konusunda hayallere dalmamış olanımız yok gibidir. Uzaydan dünyamızı ziyarete gelenler var mı gerçekten? Varsa nereden ve nasıl geliyorlar? Uzaylılar iyi mi yoksa kötü mü? Bir gün biz de evrenin çeşitli köşelerine yolculuk yapabilecek miyiz? Sahi zamanda yolculuk yapılabilir mi? Bu sorulara yanıt vermek bugün için zor olabilir. Ama hayal gücümüzü alabildiğine özgür bırakıp düşler kurmamız için de bir engel yok. Bu romanda iki kardeş kendilerini ister istemez bir yolculukta buluyor ve evrenin derinliklerinde çeşitli maceralara atılıyorlar.', publishing_house: 'Yitik Ülke Yayınları', category_id: 2, writer_id: 15},

  # Hobi
  {name: 'Dört Anlaşma', published_at: '1999', description: "Sinema dünyasının üstün zekalı oyuncularından Sharon Stone ve Jody Foster bu kitabı çevresindeki insanlara öneriyor. Amerika'nın önde gelen Yeni Çağ yazarları bu kitabı sizlere öneriyor.'Don Miguel Ruiz'in kitabı aydınlanmanın ve özgürlüğün bir yol haritasıdır.'Deepek Chopra Başarının Yedi Ruhsal Yasası kitabının yazarı 'Büyük dersler içeren ilham verici bir kitap.'Wyne Dyer Kendin Olmak kitabının yazarıCastaneda geleneğinde, Ruiz temel Toltek bilgeliğini paylaşıyor. Modern dünyada yaşayan kadınlara ve erkeklere Dingin Savaşçı olarak yaşamanın pratik uygulamalarını sunuyor.", publishing_house: 'Ötesi Yayıncılık', category_id: 2, writer_id: 16},
  {name: 'Karatay Mutfağı', published_at: '2012', description: "'Türkiye'yi zayıflatan profesör' olarak ünlenen ve ilk iki kitabı satış rekorları kıran Prof. Canan Efendigil Karatay, bu kez sizin için 'kalıcı kilo verdiren' doğal ve lezzetli yemek tariflerini seçti. Karatay Mutfağı, Türk mutfağının en güzel örneklerini Karatay prensiplerine göre revize ederek sunuyor.", publishing_house: 'Hayykitap', category_id: 2, writer_id: 17},
  {name: "Şimdi'nin Gücü ", published_at: '2001', description: "Üstat Eckhart Tolle kısa sürede bir bestseller haline gelen bilgelik dolu bu eserinde bilincimizde ve yaşamımızda mucizevi bir değişiklik yaratabilecek evrensel bir öğreti sunuyor.Tolle,tüm ıstırap,endişe ve korkularımızın dolayısıyla mutsuzluğumuzun gerçek kaynağını çarpıcı bir biçimde gösterip,onu şimdi ve burada nasıl aşabileceğimizi,huzur ve mutluluğa hemen şimdi nasıl kavuşabileceğimizi,bilincimizi hemen şimdi dönüşüme uğratıp nasıl aydınlanabileceğimizi anlatıyor.Eleştirmenler böyle bir kitabın çok nadir olarak geldiği konusunda görüş birliğine varırken,okurlar yaşamlarında olağanüstü değişimlerin meydana geldiğini bildiriyorlar.Şimdi'nin Gücü yaşamımızın her anının bir mucize olduğunu fark etmemizi sağlıyor ve büyük bir yetkinlikle Şimdinin Gücüne nasıl erişebileceğimizi açıklıyor.", publishing_house: 'Akaşa Yayın', category_id: 2, writer_id: 18},
  {name: 'Kayıp Kıta Mu', published_at: '16.06.2015', description: "Eskiden bilim insanları Pasifik Okyanusu'nun ortasında Mu gibi devasa bir kıtanın var olduğu fikrine oldukça kuşkuyla yaklaşıyorlardı. Ancak, bugüne dek yapılan araştırmalar sonucunda böyle bir kıtanın varlığını kanıtlayan verilere ulaşıldı. Hindistan'daki bir tapınakta bulunan ve bilgili bir rahibin yardımıyla şifreleri çözülen kutsal tabletler bu veriler arasında önemli bir yer tutar. Valmiki'nin kaleme aldığı klasik Hint destanı Ramayana gibi metinlerde de Mu'nun varlığı teyit edilir. Valmiki, ayrıca Ramayana'da Nakalların Burma'ya Pasifik Okyanusu'ndan geldikleri bilgisini de verir. Kayıp Kıta Mu'nun varlığına işaret eden başka bir veri de konumları ve üzerlerindeki semboller yoluyla Mu'nun insanlığın anavatanı olduğu bilgilerini taşıyan harabelerdir. Mısır, Burma, Hindistan, Japonya, Çin, Güney Denizi Adaları, Orta Amerika, Güney Amerika ile bazı Kuzey Amerika Kızılderili kabileleri ve diğer eski medeniyetlerin yaşadığı yerlerde bulunan eski semboller ve sürdürülen geleneklerin evrensel bir niteliğe sahip oluşu da bu veriler arasında yer alır. Kayıp Kıta Mu, ömrünü neredeyse bu konuya harcayan James Churchward'ın Mu araştırmaları hakkındaki temel bilgilerini içeren ilk kitabıdır.", publishing_house: 'Omega', category_id: 2, writer_id: 19},
  {name: 'Elfabe', published_at: '16.06.2015', description: 'El ve yüz çizgilerinden, tavır ve davranışlarından insanların kabiliyet ve kapasitelerini okuma sanatı olan ELFABE, insanın yüzündeki, avucundaki, cildindeki birtakım işaretlerden hareket ederek, hayatını doğru yönlendirmesi için ona yardımcı olmak amacıyla yazılmış bir kitap... Genetik potansiyelini keşfetmek isteyenlere kaynak niteliğinde bir eser...', publishing_house: 'Hayat Yayıncılık', category_id: 2, writer_id: 20},

  # Bilim kurgu
  {name: 'Otostopçunun Galaksi Rehberi ', published_at: '18.07.1979', description: 'Tamamen sakin bir hayat yaşamak, hayatına temel yaşamsal fonksiyon olarak soğuk bira ve güzel çay içmek kavramını oturtmak isteyen, kendi halinde, üstelik fazlasıyla uysal bir adam Arthur Dent, bir sabah uyanır ve evinin saçma bir nedenle yıkılacağını öğrenir; ama bu yalnızca başlangıçtır. Daha bir kaç saat bile geçmeden gezegeni yok edilecek ve yanında kankası Ford Prefect, üstünde yıpranmış sabahlığı, elinde havlusuyla galaksi boyunca sürecek inanılmaz bir yolculuğa çıkacaktır.', publishing_house: 'Kabalcı Yayınevi', category_id: 3, writer_id: 21},
  {name: 'Bioshock: Rapture Şehri', published_at: '17.03.2016', description: "Dünyanın en çok satan bilgisayar oyunlarından Bioshock'ın başlangıç hikâyesi… Su altı şehri Rapture'ın bilinmeyen gerçekleri… Bir ütopyanın adım adım distopyaya dönüşmesi… II. Dünya Savaşı'nın sonuydu. Franklin D. Roosevelt'in Yeni Düzen'i, Amerika siyasetinin gidişatını değiştirmişti. Vergiler hiç olmadığı kadar yüksekti. Hiroşima ve Nagazaki'ye atılan atom bombaları, tüm dünyaya toplu bir ölüm korkusu saldı. Hükümetlerin gizli ajanlıklarının ve birimlerinin yükselişi, dikkatleri üzerine çekiyordu. Amerika'nın özgürlük anlayışı yok oluyordu ve pek az insan özgürlüklerini kazanmak için savaşmaya hazırdı.", publishing_house: 'İthaki Yayınları', category_id: 3, writer_id: 22},
  {name: 'Doctor Who Savaş Makineleri', published_at: '17.03.2016', description: "Büyük Zaman Savaşı ve Savaş Doktoru'na dair şimdiye dek anlatılan en detaylı hikâye!", publishing_house: 'İthaki Yayınları', category_id: 3, writer_id: 23},
  {name: 'Metro 2033', published_at: '16.06.2015', description: "Yıl 2033... Nükleer savaş sonrası enkaz haline gelen dünyada insan soyu neredeyse tükenmiş, radyasyon yüzünden kentler yaşanamaz halde... Hayatta kalan birkaç bin kişi yeraltına, dünyanın en büyük nükleer sığınağı olan Moskova Metrosu'na sığınıyor. Burası insanoğlunun son kalesi. Yeraltındakiler için en büyük tehlike Karadelililer. İstasyonlar mini devletlere bölünmüş. İdealler, dinler, temiz su gibi nedenlerle bir araya gelmiş halklar. Duygular yerini içgüdülere bırakmış. Tek bir amaç var: Ne pahasına olursa olsun hayatta kalmak. Genç Artyom'a, yaklaşmakta olan karanlık tehlikeye karsı halkı uyarmak için Metro'nun kalbi, Polis istasyonuna gitme görevi verilir. Metro'nun kaderi belki de tüm insanlığın kaderi Artyom'un elindedir artık...", publishing_house: 'Panama Yayıncılık', category_id: 3, writer_id: 24},
  {name: 'Marslı', published_at: '18.07.2014', description: "Altı gün önce, Mark Watney Mars'a ayak basan ilk insanlardan biriydi. Şimdi ise, orada ölmesi neredeyse kesin.", publishing_house: 'İthaki Yayınları', category_id: 3, writer_id: 25},

  # Araştırma-tarih
  {name: 'Hayvanlardan Tanrılara- Sapiens', published_at: '17.03.2016', description: "Çoğu çalışma insanlığın serüvenini ya tarihi ya da biyolojik bir yaklaşımla ele alır, ancak Harari 70 bin yıl önce gerçekleşen Bilişsel Devrim'le başlattığı bu kitabında gelenekleri yerle bir ediyor. İnsanların küresel ekosistemde oynadıkları rolden imparatorlukların yükselişine ve modern dünyaya kadar pek çok konuyu irdeleyen Sapiens, tarihle bilimi bir araya getirerek kabul görmüş anlatıları yeniden ele alıyor.", publishing_house: 'Kolektif Kitap', category_id: 3, writer_id: 26},
  {name: 'Osmanlı Tarihinde İslamiyet ve Devlet- Seçme Eserleri 9', published_at: '17.03.2016', description: "Osmanlı Devleti bu geleneğin bir parçasıydı. Yaygın popüler kanının aksine, her devlet gibi başlangıçta belli bir kalıpla kurulmuş, çöküşüne dek de bu kalıba harfiyen uymuş değildi. Halil İnalcık, Osmanlı tarihinin geçmişe uzanan köklerini de göz ardı etmeden, 600 yıl boyunca devlet ve İslamiyet arasındaki değişken ilişkinin bir dökümünü bu kitapta sunuyor. Kutadgu Bilig'deki devlet anlayışından başlayarak, Uc'larda bir yanda gâzî beylerle, bir yanda dervişlerle başlayan kuruluş öyküsünü anlatıyor. Devlet kurumsallaştıkça Uc'ların, gâzîlerin ve dervişlerin önemlerini kaybedişini, bu arada yeni kurumların ve anlayışların yükselişini gözler önüne seriyor. Fatih Kanûnnamesi'yle örfün hukuk alanına resmen girişinin, ulemanın devlet yapısındaki diğer unsurlardan giderek ayrışmasının uzun zamana yayılmış öyküsünü ayrıntılarıyla sunuyor. 17. Yüzyılda Avrupa'daki tasfiyeci akımlarla aynı sıralarda ortaya çıkan selefî Kadızâdelilerin hem toplum hem de devlet ve İslâmiyet üzerindeki etkilerini mercek altına alıyor.18. yüzyılda başlayan Batılılaşma eksenli modernleşme hareketinin Cumhuriyet'in kuruluşuna dek uzanan seyrini takip ediyor. Osmanlıların kuruluş yıllarından beri süren Hıristiyanlık İslâm tartışmalarını da bu çerçevede ele alıyor. Osmanlı Tarihinde İslamiyet ve Devlet kadim bir meseleyi, usta bir Osmanlı tarihçisinin kaleminden okumak isteyenler için.", publishing_house: 'İş Bankası Kültür Yayınları', category_id: 3, writer_id: 27},
  {name: 'Türklerin Tarihi- 2', published_at: '17.03.2016', description: "Türklerin Tarihi kitabında Marmara'da küçük bir beylik olarak doğan, gelişen ve kuruluşunun üzerinden 150 yıl geçmeden Balkanlar'da ve Ege'de hâkimiyet tesis eden, Akdeniz dünyasının son muhteşem imparatorluğu olan Türk İmparatorluğu'nun üç kıtaya yayılmasına şahitlik edeceksiniz. Sultanü'l-Berreyn ve Hakanü'l-Bahreyn (İki Karanın ve İki Denizin Hükümdarı) olan Fatih Sultan Mehmed gibi bir Rönesans hükümdarının dünyasına eşlik ederek; Türk tarihinin büyük asrı, dünya tarihinde birçok değişime neden olan 15. yüzyılın bilinmeyenlerini öğreneceksiniz… Bugün Avrupa, Balkanlar, Ortadoğu ve Kuzey Afrika'da, sayıları yirmiyi aşan çeşitli dil, din, ırk ve siyasal rejime sahip ülkenin ortak tarihini okuyacaksınız… Hepsi birbirinden değerli Türk sultanların başarılarını görecek; harp teknikleri Rönesans kadar Asyai Türk tekniklerine de dayanan dünyanın en güçlü ordusunu tanıyacak ve kısa sürede Üçüncü ve son Roma İmparatorluğu'nun nasıl kurulduğuna şahitlik edeceksiniz. Anadolu'nun bozkırlarından Avrupa'nın içlerine, İlber Ortaylı'nın satırları arasında dolaşmak isteyen her yaştan okurun zevkle okuyacağı bir başucu kitabı...", publishing_house: 'Timaş Yayınları ', category_id: 3, writer_id: 28},
  {name: "Haliç'te Yaşayan Simonlar", published_at: '2010', description: "Avcı kitabın başlığında iki metafor kullanıyor; bunların devlet görevlilerinin, belli bir ideoloji etrafında örgütlenmiş grupların ve genel anlamda toplumun zihniyetini tanımlayabilmek için ne kadar isabetli bir biçimde seçilmiş olduğunu kitabı okuyup bitirdiğinizde anlayacaksınız. Görünen değil, perde arkasındaki gerçekleri merak ediyorsanız Emniyet teşkilatının güvenilir ve öncü ismi Hanefi Avcı'nın dürüst ve cesur sesine kulak verin!", publishing_house: 'Angora', category_id: 3, writer_id: 29},
  {name: 'Komünist Manifesto', published_at: '18.04.2008', description: 'Karl Marx ve Friedrich Engels´in, Komünistler Birliği´nin programı olarak kaleme aldıkları Komünist Manifesto, 1848 Şubat´ında, tüm Avrupa´nın devrimci ayaklanmalarla çalkalandığı bir dönemde, Londra´nın gösterişsiz bir basımevinde basıldı. Bilimsel sosyalizmin kitlesel siyaset sahnesine çıkışının ilk ciddi işareti olan Manifesto, yayınlandığı günden bu yana en çok okunan ve en çok tartışılan toplumsal ve siyasal metinlerden biri olmakla kalmadı, daha sonraki sosyalist ve komünist partilerin programlarının temelini oluşturdu, dünyanın değişmesinde ve milyonlarca insanın yaşamında belirleyici bir rol oynadı. Modern çağda başka hiçbir siyasal hareket, döneminin toplumsal, ekonomik ve sınıfsal koşullarını kavrayışındaki derinlik, çözümleyişindeki gözüpeklik ve üslubunun gücü bakımından, Manifesto´yla kıyaslanabilecek bir metin ortaya çıkaramadı. Bugün Marxçı hareketin temel belgesi ve devrimci bir klasik sayılan Komünist Manifesto´yu, Marx ve Engels´in daha sonraki basımlara yazdıkları önsözler eşliğinde, Celâl Üster ve Nur Deriş´in 1978´de yaptıkları çevirinin gözden geçirilmiş basımıyla ve Manifesto´nun Türkiye ve Türkçedeki serüvenine ışık tutan bir önsözle sunuyoruz ...', publishing_house: 'Can Yayınları', category_id: 3, writer_id: 30},

  # Macera-polisiye
  {name: 'Cehennem', published_at: '18.07.2013', description: 'Harvard Üniversitesi Simgebilim Profesörü Robert Langdon başından vurulmuş bir halde hastane odasında gözlerini açar. Ne buraya nasıl geldiğini ne de nasıl vurulduğunu hatırlamaktadır. Camdan gördüğü manzara karşısında altüst olan profesör, evinden binlerce kilometre uzakta, Floransa’da olduğunu anlar. Yaşadığı korkunç baş ağrısına eşlik eden tek şey; sürekli kâbuslarında gördüğü kan kırmızısı bir nehrin karşısından kendisine seslenen gümüş saçlı güzel bir kadın ve toprağa baş aşağı gömülü can çekişen bedenlerdir. Langdon gördüğü kâbusları anlamlandırmaya çalışırken kadın bir suikastçı tarafından takip edildiğini, kendine tedavi uygulayan doktorlardan biri gözlerinin önünde vurulunca anlar. Hastanede görevli diğer doktorlardan biri olan Sienna Brooks’un o ölüm kalım anında yardım etmesiyle hayatta kalır. Simgebilim profesörü kendini bir anda ipuçlarını Dante’nin cehenneminde bularak çözmesi gereken korkunç bir senaryonun içinde bulur. Floransa’nın tarih kokan dar sokaklarından Venedik’in muazzam bazilikalarına uzanan semboller zinciri Langdon’ı insanlık tarihini sonsuza dek değiştirebilecek bir mekâna sürükler. Burası üç imparatorluğun merkezi olmuş, insanlık tarihi kadar eski, dünyanın incisi İstanbul’dur. Ve bu şehirde ya insanlık tarihi baştan sona yeniden yazılacak ya da bunu yazacak hiç kimse kalmayacaktır...', publishing_house: 'Altın Kitaplar', category_id: 4, writer_id: 31},
  {name: 'Oz', published_at: '17.08.2016', description: "Dorothy ilk defa öldüğünde on iki yaşındaydı. En azından bana söylediği buydu. Delirdiğini düşünmüştüm ama şimdi ona inandığım için esas deli ben miyim diye merak ediyorum. Öyleysem bunların hiçbirinin önemi yok demektir. Ama değilsem… Eh, o zaman dünya benim düşündüğüm gibi bir şey değil demektir. Üstelik tek bir dünya yok. Kafanız karıştıysa canınız sıkılmasın. Benimki de karışmıştı. Okuyun, anlayacaksınız. Sonra karar verirsiniz: Ben mi delirdim yoksa siz mi? Hortum seni sürükledi. Şimdi hikâyeye baştan başlayacaksın. Aklını, kalbini, duyularını karıştıracak bir dünyayla karşı karşıyasın. Bu diyarda gündüzler karanlık turuncu, güneş siyah, geceler bembeyaz. Büyünün yerini bilim aldı. Hatırladığın herkes, her şey artık çok daha güzel, korkunç, acımasız. Yeniden keşfetmeye hazırlan: OZ'u ya da kendini!", publishing_house: 'April Yayıncılık', category_id: 4, writer_id: 32},
  {name: "Beyoğlu'nun En Güzel Abisi", published_at: '16.06.2015', description: "Yılbaşı gecesi işlenen bir cinayet... Tarlabaşı'nın arka sokaklarında bulunan bir erkek cesedi. Öldürülmüş erkeklerin en yakışıklısı, belki de en kötüsü. Karanlık sırların ortaya çıkardığı utanç verici bir gerçek. Gururlarının kurbanı olmuş erkekler, onların hayatlarını yaşamak zorunda olan kadınlar. Bu cinayetler yatağında, bu kötülükler bahçesinde, bu insan eti satılan can pazarında masumiyetini korumaya çalışan bir adam. Bir zamanlar İstanbul'un en gözde yeri olan Beyoğlu'nun hazin hikâyesi. ", publishing_house: ' Everest Yayınları  ', category_id: 4, writer_id: 33},
  {name: 'Trendeki Kız', published_at: '17.08.2016', description: 'Rachel her gün aynı trene binip aynı çifti izliyordu. Çiftin başına gelenleri bütün ülke duyduktan sonra, hayatlarına dâhil olmaya karar verdi.', publishing_house: 'İthaki Yayınları', category_id: 4, writer_id: 34},
  {name: "Assassin's Creed Yoldaşlık", published_at: '18.07.2014', description: "Ezio'nun serüveni onu sınırlarını zorlayana dek sınayacaktı. Babası Papa'dan daha alçak ve daha tehlikeli olan Cesare Borgia, İtalya'yı fethedene kadar rahat etmeyecekti. İhanet dolu bu gibi zamanlarda komplo her yerde kol gezecekti; Yoldaşlık üyeleri arasında bile…", publishing_house: 'Epsilon Yayınları', category_id: 4, writer_id: 35},

  # Romantik
  {name: 'Senden Önce Ben', published_at: '17.08.2016', description: "Birbirlerine aşktan başka verecek hiçbir şeyleri yoktu... Yaşamın ince detayları Lou'dan sorulur. Otobüs durağıyla ev arasında kaç adım var? Çalıştığı kafeye gelip gidenler nasıl bir hayat yaşıyor? Parlak yeşil elbisenin altına ne renk külotlu çorap giyilir? Onda bu soruların hepsinin cevabı var. Kolayca mutlu olabildiği küçücük dünyasında bilmediği tek şey hayatın çok daha karmaşık soru ve cevaplarla dolu olduğu... Geçirdiği motosiklet kazasıyla hayatı altüst olan Will uzun süredir karmaşık sorularla meşgul. Bu hayatta diğer insanları mutlu eden küçük şeyler ona biraz olsun keyif vermiyor. Çevresindeki tüm renkler birden griye dönmüş ve böyle bir umutsuzluk içindeyken yapabileceği tek şeyin hayatını sonlandırmak olduğunu düşünüyor.", publishing_house: 'Pegasus', category_id: 4, writer_id: 36},
  {name: 'Eleanor - Park', published_at: '18.07.2013', description: "İlk aşkın sonsuza dek sürmeyeceğini bilecek kadar zeki ama bunu deneyecek kadar cesur ve umutsuz, on altı yaşındaki iki talihsiz âşığın bir okul yılı boyunca süren hikâyesi. Eleanor, Park'la karşılaştığında siz de ilk aşkınızı ve nasıl da büyülendiğinizi hatırlayacaksınız...", publishing_house: 'Pegasus', category_id: 4, writer_id: 37},
  {name: 'Aynı Yıldızın Altında', published_at: '2012', description: "On altı yaşındaki kanser hastası Hazel Grace'in birkaç yıl daha yaşamasını garanti eden tıp mucizesine rağmen hastalığı ölümcüldür ve konulan teşhisle birlikte yıldızlar, öyküsünün son bölümünü çoktan kaleme almıştır. Fakat Augustus Waters isimli yakışıklı bir sürpriz karakter, Kanserli Çocuklar İçin Destek Grubu'nda boy gösterince Hazel'ın hayatı bambaşka bir yöne sapar ve bu zeki çocuğun çekimine karşı koyamayan kızın öyküsü yeniden yazılır...", publishing_house: 'Pegasus', category_id: 4, writer_id: 38},
  {name: 'Tersyüz', published_at: '17.08.2016', description: "Ambrose Young okulun en çekici çocuğu ve kasabanın yıldız güreşçisiydi. Uzun boylu ve yapılı bir vücudu, omuzlarına değen saçları ve yakıcı gözleriyle aşk romanlarının kapaklarını süsleyebilecek kadar yakışıklıydı. Fern Taylor bunun farkındaydı ve Ambrose Young'a âşıktı. Belki de bu kadar yakışıklı olduğu için Fern asla onunla birlikte olabileceğini düşünmemişti. Ta ki her şey tersyüz olana ve Ambrose'un eski yakışıklılığından eser kalmayana kadar… Tersyüz, beş genç adamın küçük bir kasabadan kalkıp savaşa gidişinin ve içlerinden sadece birinin geri dönüşünün hikâyesi... Hayatı, benliği, güzelliği kaybetmenin hikayesi... Bir kızın, yıkılmış bir çocuğa ve yaralı bir savaşçının, sıradan bir kıza olan aşkının hikâyesi... Kalp kırıklığının üstesinden gelen bir arkadaşlığın ve bilinen kalıpların dışına çıkan bir kahramanın hikayesi... Tersyüz, hepimizin içinde biraz iyiliğin biraz da kötülüğün olduğunu keşfettiğimiz modern çağın Güzel ve Çirkin'i...", publishing_house: 'Yabancı', category_id: 4, writer_id: 39},
  {name: 'Sputnik Sevgilim', published_at: '13.08.2016', description: "Sen benim bir parçamsın... Ben âşık oldum. Şüphe yok. Buz soğuktur, gül kırmızı. Ve bu aşk beni sürükleyip bir yerlere götürmeye çalışıyor; öyle güçlü bir akıntı ki ondan kendimi korumam neredeyse olanaksız. Ama artık dönüş yok. Kendimi bu akıntıya bırakmak dışında bir şey yapamam. Yanıp kül olsam da, yok olup gitsem de. Japonya'dan bir Yunan adasına uzanan, üç kişiyi birbirine kenetleyen büyüleyici bir aşkın hikâyesi. Haruki Murakami'den düşlerinize sızacak bir roman...", publishing_house: 'Doğan Kitap', category_id: 4, writer_id: 40}
].each do |b|
  b[:image] = File.open("/home/gizem/Pictures/lastloginsusers.png")
  bs << Book.create(b)
end

puts "seed done"
